# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            pSeudo Thought
tagline:          "Writing 'em down to help other"
description:      'A silly attempt to mirror my thought on papper from so called brain'
url:              http://dharmeshpandav.github.io/
baseurl:          '/'
paginate:         5

author:
  name: 'Dharmesh Pandav'
  email: dharmesh.pandav@privatenode.in


# Custom vars
version:          1.0.0
comments:         True

github:
  repo:           https://github.com/dharmeshpandav/dharmeshpandav.github.io
