# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            pSeudo Thought
tagline:          "<sup>beta*</sup> Writing 'em down to help other"
description:      'A silly attempt to mirror my thought on papper from so called brain'
url:              http://dharmeshpandav.github.io/
baseurl:          '/'
paginate:         5

author:
  name: 'Dharmesh Pandav'
  email: dharmesh.pandav@privatenode.in
  github: dharmeshpandav
  twitter: dharmeshpandav
  linkedin: dharmeshpandav
  goodreads: dharemeshpandav
  disqus_shortname: mrpandav
  google_analytics_id:  UA-55164623-2
  google_analytics_url: dharmeshpandav.github.io
  bio: MS in Information and Technology DAIICT,Gandhinagar,India

# Custom vars
version:          1.0.0
comments:         True

github:
  repo:           https://github.com/dharmeshpandav/dharmeshpandav.github.io
