# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            pSeudo Thought *Beta*
tagline:          'Write em down to help other '
description:      'A silly attempt to mirror my thought on Papper from so called brain'
url:              http://privatenode.in

author:
  name:           'Dharmesh Pandav'
  url:            https://twitter.com/DharmeshPandav

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/dharmeshpandav/dharmeshpandav.github.io
