# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            pSeudo Thoughts
tagline:          "Writing 'em down to help other"
description:      'A silly attempt to mirror my thoughts on blog from so called brain'
url:              http://blog.privatenode.in
baseurl:          '/'
paginate:         5
#excerpt_separator: <!--more-->
excerpt_seprator: ''

author:
  name: 'Dharmesh Pandav'
  email: dharmesh.pandav@privatenode.in
  github: dharmeshpandav
  twitter: dharmeshpandav
  linkedin: dharmeshpandav
  goodreads: dharmeshpandav
  disqus_shortname: mrpandav
  google_analytics_id:  UA-55164623-2
  google_analytics_url: dharmeshpandav.github.io
  bio: MS in Information and Technology DAIICT,Gandhinagar,India

# Custom vars
version:          1.0.0
comments:         True

github:
  repo:           https://github.com/dharmeshpandav/dharmeshpandav.github.io
