# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            pSeudo Thought <em>Beta<em>
tagline:          'Writing em down to help other '
description:      'A silly attempt to mirror my thought on papper from so called <strong>brain<strong>'
url:              http://dharmeshpandav.github.io/
baseurl:          '/'

author:
  name:           'Dharmesh Pandav'
  url:            https://twitter.com/DharmeshPandav

paginate:         5

# Custom vars
version:          1.0.0
comments:         True

github:
  repo:           https://github.com/dharmeshpandav/dharmeshpandav.github.io
